#
# Golang CI pipeline configuration
#
# To execute linters in local the ./scripts/lint.sh script can be used.

linters:
  disable-all: true

  # Run golangci-lint linters to see
  enable:
    - gci # Gci controls golang package import order and makes it always deterministic. [fast: true, auto-fix: false]
    - gofmt # Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification [fast: true, auto-fix: true]
    - gofumpt # Gofumpt checks whether code was gofumpt-ed. [fast: true, auto-fix: true]
    - goimports # In addition to fixing imports, goimports also formats your code in the same style as gofmt. [fast: true, auto-fix: true]
    - whitespace # Tool for detection of leading and trailing whitespace [fast: true, auto-fix: true]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - stylecheck
        - gosec
