# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test-go-1-12:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go mod download
      - run:
          name: Run unit tests
          command: go test -v ./...
  test-go-1-10:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/scaleway/scaleway-sdk-go
    steps:
      - checkout
      - run: go get -t
      - run:
          name: Run unit tests
          command: go test -v ./...
workflows:
  version: 2
  test:
    jobs:
      - test-go-1-12
      - test-go-1-10
